### ISSUE TITLE
tasks when dropping sonata admin 2.2 support

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataDoctrinePhpcrAdminBundle#294]
Tasks to do when dropping support for sonata admin 2.2.

* [ ] remove bootstrap2 classes (icon-plus and friends) when dropping support for 2.2 - see #290 / #293
* [ ] remove dependency on jquery bundle and update doc that user needs to care about jquery. see #304
* [ ] Update all admins the CMF bundles provide to use tabs where appropriate. See https://github.com/symfony-cmf/cmf-sandbox/issues/273#issuecomment-60379640

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
