### ISSUE TITLE
SonataAdminBundle 3.0 support

### ISSUE THREAD

**Issue by lsmith77** [sonata-project/SonataDoctrinePhpcrAdminBundle#338]
This is just a ticket that tracks all the tickets related to this topic.

https://github.com/symfony-cmf/TreeBrowserBundle/milestones/2.0%20FancyTree%20&%20Resource
https://github.com/symfony-cmf/RoutingBundle/issues/284
https://github.com/symfony-cmf/SimpleCmsBundle/issues/131
https://github.com/symfony-cmf/CoreBundle/pull/157
https://github.com/symfony-cmf/SeoBundle/pull/208
https://github.com/symfony-cmf/ContentBundle/pull/125
https://github.com/symfony-cmf/MenuBundle/pull/219
cc @WouterJ

**Comment by lsmith77** [comment]
https://github.com/symfony-cmf/TreeBrowserBundle/milestones/2.0%20FancyTree%20&%20Resource

**Comment by lsmith77** [comment]
https://github.com/symfony-cmf/RoutingBundle/issues/284
https://github.com/symfony-cmf/SimpleCmsBundle/issues/131
https://github.com/symfony-cmf/CoreBundle/pull/157
https://github.com/symfony-cmf/SeoBundle/pull/208
https://github.com/symfony-cmf/ContentBundle/pull/125
https://github.com/symfony-cmf/MenuBundle/pull/219

**Comment by rusanter** [comment]
What the minimum list of tickets should be done to safely use this bundle with Sonata Admin 3?
The current list of milestone 2.0 tickets seems quite long and pessimistic.

**Comment by ElectricMaxxx** [comment]
I changed the list in a ToDo list to check them all:

* [ ] https://github.com/symfony-cmf/TreeBrowserBundle/milestones/2.0%20FancyTree%20&%20Resource
* [ ] symfony-cmf/routing-bundle#284
* [ ] symfony-cmf/simple-cms-bundle#131
* [ ] symfony-cmf/core-bundle#157
* [ ] symfony-cmf/seo-bundle#208
* [ ] symfony-cmf/content-bundle#125
* [ ] symfony-cmf/menu-bundle#219

**Comment by ElectricMaxxx** [comment]
All the tabs has been implemented in sonata-phpcr-admin-integration-bundle, so lets lift the version here.

**Comment by wouterj** [comment]
Well, 2.0 has a lot more issues than this one: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0

**Comment by ElectricMaxxx** [comment]
The Bundle is currently working with `"sonata-project/admin-bundle": "^3.1"` So this issue should be solved.

@dbu @wouterj ping.

**Comment by ElectricMaxxx** [comment]
@wouterj i know that is the milestone. But the issue should make sonata-admin 3.0 possible, and that should work now.

**Comment by dbu** [comment]
quite some things in that list are very old. we seem to have had the good intention of wanting to fix them, but they seem no blockers for a 2.0 release. i agree with max that sonata admin 3 support seems solved. and i think we should throw all other issues out of the 2.0 milestone unless somebody feels like wanting to fix one of them very soon.

**Comment by ElectricMaxxx** [comment]
So I will close this ticket.
